export type Language = {
	frequency: string;
	monthly: string;
	monthlyDonation: string;
	oneTimeDonation: string;
	amount: string;
	amountError: string;
	frequencySelect: string;
	frequencyPopover: string;
	currencyPopover: string;
	switchCurrency: string;
	noThanks: string;
	donateWithCrypto: string;
	minDonationAmount: string;
	countryTitle: string;
	countrySelection: string;
	donate: string;
	donationRedirectNotice: string;
	thanksDonation: string;
	countryDescription: string;
	chooseAnAmount: string;
	enterAnAmount: string;
};
